### ISSUE TITLE
Shortcut, bll, kelp colour

### ISSUE THREAD

**Issue by Garrakx** [Garrakx/Custom-Regions#43]

**Comment by Fyeryn** [comment]
Shortcut color is stored in the palette, gate glyph has the same color as the shortcut (except for electric gates where it's hardcoded to be yellowish), green kelp color is hardcoded to palette 13 (used in shoreline), and the brown daddy has a special behavior and not only a brown color (it doesn't eat brothers). Maybe that can help.
