### ISSUE TITLE
Add AUDB funcionality

### ISSUE THREAD

**Issue by Garrakx** [Garrakx/Custom-Regions#9]

**Comment by aaay-aaay** [comment]
If you want help with this, DM us on discord.

Although what do you mean by "AUDB functionality"? AutoUpdate support, or some other kind of interaction with AUDB?

- pastebin.com/q3BTYZc9 aka bee

**Comment by aaay-aaay** [comment]
That was meant to be a "-", we didn't know it would end up formatting like that. ._.
